spring.application.name=pkitest


# Configuración personalizada

#HSM Initialization
hsm.pkcs11.config-path=/home/juanedwinfg/Documentos/apache-tomcat-11.0.20/webapps/pkcs11.config

hsm.pkcs11.User0=EECF7DC7F3ADE3F73DA9A2CEEAF3

#Datos de SQL
spring.datasource.url=jdbc:postgresql://localhost:5432/TestPKI
spring.datasource.username=postgres
spring.datasource.password=24je11fg91
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Esto ayuda a que Spring no intente recrear las tablas si ya las hiciste con el script
spring.jpa.hibernate.ddl-auto=validate
