spring.application.name=pkitest


# Configuración personalizada

#HSM Initialization
hsm.pkcs11.config-path=/home/juanedwinfg/Documentos/apache-tomcat-11.0.20/webapps/pkcs11.config

hsm.pkcs11.User0=EECF7DC7F3ADE3F73DA9A2CEEAF3
