spring.application.name=pkitest



#HSM Initialization
hsm.pkcs11.config-path=/home/juanedwinfg/Documentos/apache-tomcat-11.0.20/webapps/pkcs11.config

hsm.pkcs11.User0=EECF7DC7F3ADE3F73DA9A2CEEAF3

#Datos de SQL
spring.datasource.url=jdbc:postgresql://localhost:5432/TestPKI
spring.datasource.username=postgres
spring.datasource.password=24je11fg91
# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# Mostrar el SQL en consola para auditoría (opcional)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# IMPORTANTE: Para que la validación no falle con los tipos ENUM de Postgres
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false


# Mostrar logs de tu paquete
logging.level.com.pki.pkitest=DEBUG
# Mostrar logs detallados de cuando algo sale mal en el Dispatcher
logging.level.org.springframework.web=DEBUG

#Datos de Base Datos

# Configuración para el certificado ca_MTLS
app.ca.mtls.alias=CA_MTLS
app.ca.mtls.id=3a388685-c06d-4dd1-9a9a-314c182e3e6c

# Configuración para el certificado cs_KRD
app.ca.KRD.alias=CA_KRD
app.ca.KRD.id=c8af09e8-fe7c-4c95-abcd-3b6daf930cf4

# Configuración para el certificado cs_KDH
app.ca.KDH.alias=CA_KRD
app.ca.KDH.id=981f51a0-bd56-415e-a824-1ba85973de36



# Configuración para el certificado Root
app.ca.ROOT.alias=CA_ROOT
app.ca.ROOT.id=f7a98c0a-ee41-47ae-9694-9c9083bfa0e9

